/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hello */

#ifndef _Included_hello
#define _Included_hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hello
 * Method:    helloWorld
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_hello_helloWorld
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
